"""Synthetic diagnostics of the spatial operating-point estimator.

Writes <out>/estimator_sanity.md and <out>/estimator_sanity.csv (default
out = tables/). No EEG data are used. All numbers in the report are produced
by this script.

Usage: python scripts/estimator_sanity.py [--out tables]
"""
from __future__ import annotations

import argparse
import csv
import os
import sys

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, os.path.join(ROOT, "src"))
from eegop.estimators import (_direction_scores,  # noqa: E402
                              estimate_spatial_operating_point)


def spectrum(covs, priors, score):
    classes = np.arange(len(covs))
    cc = {k: covs[k] for k in classes}
    mix = sum(priors[k] * covs[k] for k in classes)
    C = mix.shape[0]
    reg = 1e-4 * np.trace(mix) / C
    m, W = _direction_scores(cc, np.asarray(priors), classes, mix, C, reg, score=score)
    return m, W, reg, np.linalg.eigvalsh(mix)


def simulate(covs, n_trials, T, rng):
    """Zero-mean Gaussian epochs, one covariance per class; returns X (N,C,T), y."""
    X, y = [], []
    for k, S in enumerate(covs):
        L = np.linalg.cholesky(S)
        for _ in range(n_trials):
            X.append(L @ rng.standard_normal((S.shape[0], T)))
            y.append(k)
    return np.asarray(X), np.asarray(y)


def rand_spd(C, rng, cond=100.):
    Q, _ = np.linalg.qr(rng.standard_normal((C, C)))
    ev = np.logspace(0, np.log10(cond), C)[::-1]
    return (Q * ev) @ Q.T


def pr(m):
    mp = m[m > 0]
    return (mp.sum() ** 2 / (mp ** 2).sum()) if mp.size else np.nan


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--out", default=os.path.join(ROOT, "tables"))
    args = ap.parse_args()
    est = estimate_spatial_operating_point
    rows, lines = [], []

    rng = np.random.default_rng(0)
    lines.append("# Estimator sanity diagnostics (synthetic)\n")
    lines.append("Generated by `scripts/estimator_sanity.py`. All quantities are computed from "
                 "known population covariances or simulated Gaussian data; no EEG is used.\n")

    # 1. population equal-covariance case ------------------------------------
    lines.append("## 1. Equal class covariances (population, no sampling noise)\n")
    C = 22
    S = rand_spd(C, rng, cond=1e4)
    m_std, _, reg, lam = spectrum([S, S], [0.5, 0.5], "standard")
    m_jg, _, _, _ = spectrum([S, S], [0.5, 0.5], "jensen")
    pred = 0.5 * np.log2(1 + reg / np.sort(lam))  # ascending eigenvalues -> descending offset
    lines.append(f"C = {C}, mixture condition number 1e4, loading eps = {reg:.3e}.\n")
    lines.append(f"- Score of Eq. (1) (score='standard'): all {C} masses positive; sum = {m_std.sum():.4f} bits; "
                 f"max = {m_std.max():.4f}; min = {m_std.min():.2e}.")
    lines.append(f"- Predicted loading term 1/2 log2(1+eps/lambda_j): max |score - predicted| = "
                 f"{np.max(np.abs(np.sort(m_std) - np.sort(pred))):.2e}.")
    lines.append(f"- Jensen-gap score: max |m| = {np.max(np.abs(m_jg)):.2e} (zero up to rounding).")
    lines.append(f"- Participation ratio of the Eq. (1) masses under no class contrast: {pr(m_std):.2f} "
                 f"(largest mass on the smallest-eigenvalue direction).\n")
    rows.append(dict(test="equal_cov_population", standard_sum=m_std.sum(), jensen_max=np.max(np.abs(m_jg)),
                     standard_PR=pr(m_std)))

    # 2. off-diagonal contrast invisible to projected variances ---------------
    lines.append("## 2. Class contrast carried only by an off-diagonal covariance term\n")
    S1 = np.array([[2., .5], [.5, 1.]]); S2 = np.array([[2., -.5], [-.5, 1.]])
    m_std2, W2, reg2, _ = spectrum([S1, S2], [0.5, 0.5], "standard")
    m_jg2, _, _, _ = spectrum([S1, S2], [0.5, 0.5], "jensen")
    v = np.array([[w @ Sk @ w for w in W2.T] for Sk in (S1, S2)])
    kl = 0.5 * (np.trace(np.linalg.solve(S2, S1)) - 2 + np.log(np.linalg.det(S2) / np.linalg.det(S1)))
    lines.append("Sigma_1 = [[2, 0.5], [0.5, 1]], Sigma_2 = [[2, -0.5], [-0.5, 1]], equal priors; "
                 "mixture = diag(2, 1).\n")
    lines.append(f"- Projected class variances per whitening direction (rows = classes): {np.round(v, 6).tolist()}.")
    lines.append(f"- Jensen-gap masses: {np.round(m_jg2, 8).tolist()}; Eq. (1) masses: {np.round(m_std2, 6).tolist()} "
                 "(loading term only).")
    lines.append(f"- KL(N(0,Sigma_1) || N(0,Sigma_2)) = {kl:.4f} nats > 0: the classes are separable by "
                 "covariance, but any score built only from w_j' Sigma_k w_j in the mixture eigenbasis "
                 "assigns no contrast.\n")
    rows.append(dict(test="offdiag_contrast", jensen_max=float(np.max(np.abs(m_jg2))), kl_nats=kl))

    # 3. finite-sample null: equal-class data -----------------------------------
    lines.append("## 3. Finite-sample behaviour with no class difference\n")
    lines.append("Equal-class Gaussian data (random SPD covariance, condition number 1e3), 100 trials per "
                 "class, 500 samples per trial, 20 repetitions. r*_PR and r*_rel are the estimator outputs "
                 "(binary branch uses r*_PR).\n")
    lines.append("| C | score | r*_PR mean (range) | r*_rel mean (range) |\n|---:|---|---|---|")
    for C in (22, 64):
        for score in ("standard", "jensen"):
            prs, rels = [], []
            for rep in range(20):
                Sx = rand_spd(C, rng, cond=1e3)
                X, y = simulate([Sx, Sx], 100, 500, rng)
                out = est(X, y, sfreq=250., n_perm=0, score=score)
                prs.append(out["r_star_PR"]); rels.append(out["r_star_rel"])
            lines.append(f"| {C} | {score} | {np.mean(prs):.1f} ({min(prs)}-{max(prs)}) | "
                         f"{np.mean(rels):.1f} ({min(rels)}-{max(rels)}) |")
            rows.append(dict(test=f"null_C{C}_{score}", r_PR_mean=np.mean(prs), r_rel_mean=np.mean(rels)))
    lines.append("\nWith no class difference both scores still return a positive channel count; the "
                 "estimator does not include a test of whether any contrast exists (the parallel-analysis "
                 "count r*_PA, which is not used by the final rule, is the only null-calibrated quantity).\n")

    # 4. rank deficiency (common-average reference) -----------------------------
    lines.append("## 4. Rank-deficient montage (common-average reference)\n")
    C = 22
    Sa = rand_spd(C, rng, cond=1e2); Sb = Sa.copy(); Sb[:4, :4] *= 1.6   # contrast on channels 0-3
    H = np.eye(C) - np.ones((C, C)) / C
    X, y = simulate([Sa, Sb], 100, 500, rng)
    Xcar = np.einsum("ij,njt->nit", H, X)
    for lab, XX in (("original", X), ("CAR (rank C-1)", Xcar)):
        for score in ("standard", "jensen"):
            out = est(XX, y, sfreq=250., n_perm=0, score=score)
            top = sorted(out["channel_ranking"][:4].tolist())
            lines.append(f"- {lab}, {score}: largest mass = {out['score_per_direction'][0]:.3f} bits, "
                         f"r*_PR = {out['r_star_PR']}, top-4 channels = {top} (true contrast channels 0-3)")
            rows.append(dict(test=f"rank_{lab}_{score}", top_mass=float(out["score_per_direction"][0]),
                             r_PR=out["r_star_PR"], top4=str(top)))
    lines.append("")

    # 5. invariances --------------------------------------------------------------
    lines.append("## 5. Invariance checks\n")
    X, y = simulate([Sa, Sb], 80, 400, rng)
    base = est(X, y, sfreq=250., n_perm=0)
    g = est(7.3 * X, y, sfreq=250., n_perm=0)
    perm = rng.permutation(C)
    p = est(X[:, perm], y, sfreq=250., n_perm=0)
    mapped = perm[p["channel_ranking"][:base["r_star_PR"]]]
    Xs = X.copy(); Xs[:, 10] *= 10.
    s = est(Xs, y, sfreq=250., n_perm=0)
    base_set = set(base["channel_ranking"][:base["r_star_PR"]].tolist())
    lines.append(f"- Global amplitude scaling (x7.3): r*_PR {base['r_star_PR']} -> {g['r_star_PR']}; "
                 f"ranking identical: {bool(np.array_equal(base['channel_ranking'], g['channel_ranking']))}.")
    lines.append(f"- Channel permutation: selected set identical after mapping back: "
                 f"{set(mapped.tolist()) == base_set}.")
    lines.append(f"- Scaling one channel by 10: r*_PR {base['r_star_PR']} -> {s['r_star_PR']}; "
                 f"selected set changed: {set(s['channel_ranking'][:s['r_star_PR']].tolist()) != base_set}. "
                 "The channel score a_c sums squared whitening loadings, which depend on channel units; "
                 "channels should share units (all datasets here are in microvolts).\n")
    rows.append(dict(test="invariance",
                     global_scale_same=bool(np.array_equal(base['channel_ranking'], g['channel_ranking']))))

    # 6. mapping from spectrum to channel count -----------------------------------
    lines.append("## 6. Mapping from spectrum to channel count\n")
    lines.append("r*_PR = round((sum_j m_j^+)^2 / sum_j (m_j^+)^2) over positive masses, clipped to "
                 "[K-1, C]; r*_rel is the smallest number of sorted masses reaching 95% of the total "
                 "(C when the total is below 1e-10). The selected channels are the r* channels with the "
                 "largest a_c = sum over the top-r* directions of squared whitening loadings; because the "
                 "directions used depend on r*, rankings for different r* are not nested in general. "
                 "An effective number of latent directions is not a count of physical electrodes: each "
                 "direction generally loads on all sensors.\n")

    os.makedirs(args.out, exist_ok=True)
    with open(os.path.join(args.out, "estimator_sanity.md"), "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    keys = sorted({k for r in rows for k in r})
    with open(os.path.join(args.out, "estimator_sanity.csv"), "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=keys); w.writeheader(); w.writerows(rows)
    print("\n".join(lines))


if __name__ == "__main__":
    main()
